server:
  port: ${PORT:8080}

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.lizhao.searchhouse.config.RequestInterceptor
#logging:
#  level:
#    com:
#      lizhao: debug


spring:
  redis:
    url: ${REDIS_URL}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxx:10048/t66y
    username: root
    password: ${passowrd}
    hikari:
      maximum-pool-size: 3
  jpa:
    open-in-view: false
