server:
  port: ${PORT:8080}

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.lizhao.searchhouse.config.RequestInterceptor
logging:
  level:
    org:
      hibernate: off


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:${mysql_port}}/search_house
    username: root
    password: ${passowrd}
    hikari:
      maximum-pool-size: 3
      max-lifetime: 1800000
  jpa:
    open-in-view: false
