server:
  port: ${PORT:8080}

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.lizhao.searchhouse.config.RequestInterceptor
logging:
  level:
    org:
      hibernate: off

spring:
  datasource:
    tomcat:
      validation-query: /* ping */
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      test-on-connect: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:${mysql_port}}/search_house
    username: root
    password: ${passowrd}
  jpa:
    open-in-view: false
